// Generated by CoffeeScript 1.3.1
(function() {

  define(function() {
    /* Integrator
    */

    var Integrator;
    return Integrator = (function() {

      Integrator.name = 'Integrator';

      function Integrator() {}

      Integrator.prototype.integrate = function(particles, dt) {};

      return Integrator;

    })();
  });

}).call(this);
