// Generated by CoffeeScript 1.3.1
(function() {
  var transitions;

  transitions = ['zepto', 'mt-slide', 'mt-popup', 'mt-minimize', 'mt-object-switch'];

  define(transitions, function($, MTSlide, MTPopup, MTMinimize, MTObjectSwitch) {
    var App;
    return App = (function() {

      App.name = 'App';

      function App() {
        this.initTransitions();
      }

      App.prototype.initTransitions = function() {
        this.slide = new MTSlide($("#mt-slide"));
        this.popup = new MTPopup($("#mt-popup"));
        this.minimize = new MTMinimize($("#mt-minimize"));
        return this.objectSwich = new MTObjectSwitch($("#mt-object-switch"));
      };

      return App;

    })();
  });

}).call(this);
