// Generated by CoffeeScript 1.3.1
(function() {
  var transitions;

  transitions = ['zepto', 'mt-slide', 'mt-popup'];

  define(transitions, function($, MTSlide, MTPopup) {
    var App;
    return App = (function() {

      App.name = 'App';

      function App() {
        this.initTransitions();
      }

      App.prototype.initTransitions = function() {
        this.slide = new MTSlide($("#mt-slide"));
        return this.popup = new MTPopup($("#mt-popup"));
      };

      return App;

    })();
  });

}).call(this);
