// Generated by CoffeeScript 1.3.1
(function() {

  require.config({
    baseUrl: '/mt/js',
    paths: {
      zepto: 'zepto-rjs',
      modernizr: "libs/modernizr.foundation",
      css: 'libs/rjs-plugins/css',
      order: 'libs/rjs-plugins/order',
      text: 'libs/rjs-plugins/text',
      json: 'libs/rjs-plugins/json'
    }
  });

}).call(this);
