// Generated by CoffeeScript 1.3.1
(function() {
  var transitions;

  transitions = ['zepto', 'mt-slide'];

  define(transitions, function($, MTSlide) {
    var App;
    return App = (function() {

      App.name = 'App';

      function App() {
        this.initTransitions();
      }

      App.prototype.initTransitions = function() {
        return this.slide = new MTSlide($("#mt-slide"));
      };

      return App;

    })();
  });

}).call(this);
