// Generated by CoffeeScript 1.3.1
(function() {

  require(['libs/rjs-plugins/order!config', 'libs/rjs-plugins/order!app'], function(config, App) {
    return window.app = new App;
  });

}).call(this);
